# API list for not to do app

### Fetch all tickets
GET http://localhost:8000/api/v1

### fetch single ticket

# GET http://localhost:8000/api/v1/ticketId

### create new ticket
POST http://localhost:8000/api/v1/
Content-Type: application/json

{
    "task": "hello",
    "hr": 5
}

### delete ticket
PATCH  http://localhost:8000/api/v1/
Content-Type: application/json

{
    "_id": "hello@hi.com",
    "todo": true
}
### delete ticket
DELETE http://localhost:8000/api/v1/
Content-Type: application/json

{
    "_id": "hello@hi.com"
    
}