# API list not to do app

### Fetch all tasks
GET http://localhost:8000/api/v1/
 

### create new tasks
POST http://localhost:8000/api/v1/
Content-Type: application/json

{ 
  "task": "Coding Js",
  "hr": 100
}


### update tasks
PATCH  http://localhost:8000/api/v1/
Content-Type: application/json

{
"id": "612d7458aaf927067c2ba49a",
"todo": true
}


### Delete tasks
DELETE  http://localhost:8000/api/v1/
Content-Type: application/json

{
"ids": [
  "612d825769ecb0d7623be6a4"
]  
}

