# API list for not to do app

### Fetch all tickets
GET http://localhost:8000/api/v1

### fetch single ticket

GET http://localhost:8000/api/v1/612d7a23d5985482f1c8db4c

### create new ticket
POST http://localhost:8000/api/v1/
Content-Type: application/json

{
    "task": "hello",
    "hr": 5
} 

### update ticket
PATCH  http://localhost:8000/api/v1/
Content-Type: application/json

{
    "id": "612ecbbb2a1e6889fdeb4e0f",
    "todo": false
}
### delete ticket
DELETE http://localhost:8000/api/v1/
Content-Type: application/json

{
    "ids": ["612ecf6efaad05e9f282f1a5"]
    
}